### ISSUE TITLE
running the sample code raises errors with anthropic with "pip install aisuite[all]

### ISSUE THREAD

**Issue by echohive42** [andrewyng/aisuite#153]
a/Desktop/echo_hive_all/openai swarm/test.py"
Why did the pirate bring a ladder to the bar? Because he heard the drinks were on the house! Arrr!
Traceback (most recent call last):
  File "c:\Users\memoa\Desktop\echo_hive_all\openai swarm\test.py", line 12, in <module>
    response = client.chat.completions.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\memoa\miniconda3\envs\basic3\Lib\site-packages\aisuite\client.py", line 108, in create
    self.client.providers[provider_key] = ProviderFactory.create_provider(
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\memoa\miniconda3\envs\basic3\Lib\site-packages\aisuite\provider.py", line 46, in create_provider
    return provider_class(**config)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\memoa\miniconda3\envs\basic3\Lib\site-packages\aisuite\providers\anthropic_provider.py", line 16, in __init__
    self.client = anthropic.Anthropic(**config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\memoa\miniconda3\envs\basic3\Lib\site-packages\anthropic\_client.py", line 121, in __init__
    super().__init__(
  File "C:\Users\memoa\miniconda3\envs\basic3\Lib\site-packages\anthropic\_base_client.py", line 835, in __init__
    self._client = http_client or SyncHttpxClientWrapper(
                                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\memoa\miniconda3\envs\basic3\Lib\site-packages\anthropic\_base_client.py", line 733, in __init__
    super().__init__(**kwargs)
TypeError: Client.__init__() got an unexpected keyword argument 'proxies'

C:\Users\memoa\Desktop\echo_hive_all\openai swarm>

--------------
---------------
-----------
CODE I RAN:

`import aisuite as ai
client = ai.Client()

models = ["openai:gpt-4o", "anthropic:claude-3-5-sonnet-latest"]

messages = [
    {"role": "system", "content": "Respond in Pirate English."},
    {"role": "user", "content": "Tell me a joke."},
]

for model in models:
    response = client.chat.completions.create(
        model=model,
        messages=messages,
        temperature=0.75
    )
    print(response.choices[0].message.content)
`

**Comment by rohitprasad15** [comment]
Thanks for reporting this.
This is a dup of https://github.com/andrewyng/aisuite/issues/110
This has been fixed.
We will release a patch shortly with the fix into PyPI.
The fix is already merged in github.

**Comment by ksolo** [comment]
@echohive42 The new version has the update `0.1.7` I'm going to close this issue, please re-open it if the problem persists for you after you upgrade `aisuite`
