### ISSUE TITLE
APITimeoutError: Request timed out.

### ISSUE THREAD

**Issue by dxw2544523082** [andrewyng/aisuite#157]
Traceback (most recent call last):
  File "/home/dxw123/MyPytorchProject/client.py", line 12, in <module>
    response = client.chat.completions.create(
  File "/home/dxw123/anaconda3/envs/LLM/lib/python3.10/site-packages/aisuite/client.py", line 117, in create
    return provider.chat_completions_create(model_name, messages, **kwargs)
  File "/home/dxw123/anaconda3/envs/LLM/lib/python3.10/site-packages/aisuite/providers/openai_provider.py", line 29, in chat_completions_create
    return self.client.chat.completions.create(
  File "/home/dxw123/anaconda3/envs/LLM/lib/python3.10/site-packages/openai/_utils/_utils.py", line 275, in wrapper
    return func(*args, **kwargs)
  File "/home/dxw123/anaconda3/envs/LLM/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 859, in create
    return self._post(
  File "/home/dxw123/anaconda3/envs/LLM/lib/python3.10/site-packages/openai/_base_client.py", line 1280, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/dxw123/anaconda3/envs/LLM/lib/python3.10/site-packages/openai/_base_client.py", line 957, in request
    return self._request(
  File "/home/dxw123/anaconda3/envs/LLM/lib/python3.10/site-packages/openai/_base_client.py", line 1002, in _request
    return self._retry_request(
  File "/home/dxw123/anaconda3/envs/LLM/lib/python3.10/site-packages/openai/_base_client.py", line 1095, in _retry_request
    return self._request(
  File "/home/dxw123/anaconda3/envs/LLM/lib/python3.10/site-packages/openai/_base_client.py", line 1002, in _request
    return self._retry_request(
  File "/home/dxw123/anaconda3/envs/LLM/lib/python3.10/site-packages/openai/_base_client.py", line 1095, in _retry_request
    return self._request(
  File "/home/dxw123/anaconda3/envs/LLM/lib/python3.10/site-packages/openai/_base_client.py", line 1012, in _request
    raise APITimeoutError(request=request) from err
why？ 怎么解答

**Comment by ksolo** [comment]
@dxw2544523082 Can you provide more context such as a code sample that reproduces the error, the environment (Linux, MacOS?), versions of the libraries?
